### ISSUE TITLE
a couple of questions and requests

### ISSUE THREAD

**Issue by Amin456789** [fszontagh/sd.cpp.gui.wx#1] opened 2024-02-05 21:30 UTC
hi
thank u for this, can u realese it for us none programmers please, release an exe for example, im using windows

1. can u make a dark mode for it please
2. can u enhanced it for the feature inpainting when it released it
3. please add support for taesd and taesdxl to use them
4. please add the feature of --type for converting on the fly i need this to use sdxl turbo for q4.1
5. does it keep the model in memory or release after each generate?
6. does it support sdxl turbo
7.does it support batch image save and batch image generation with random seeds?
8. does it support cpu too?
9. does img2img works as well?
10. does it loads gguf files or only safetensors?

kind regards

**Comment by fszontagh** [comment] 2024-02-06 06:54
"can u make a dark mode for it please" 
This is not an important feature yet, i will see what can i do to implement it. 

"can u enhanced it for the feature inpainting when it released it"
I will try. Currently i want to implement a minimalistic model handling feature, img2img with controlnet

"please add support for taesd and taesdxl to use them"
The gui features are limited to the backend's features (stabble diffusion cpp).

"please add the feature of --type for converting on the fly i need this to use sdxl turbo for q4.1"
The model conversion will be implemented on the gui at the Models tab

"does it keep the model in memory or release after each generate?"
Yes. The modell is stay in memory. Eg. if you start 2 job with the same model and vae, no need to unload the model and load again in. But if you change the vae model, the model will be reloaded with the new vae model. This is the limitation of the backend. 

"does it support sdxl turbo"
"does it support batch image save and batch image generation with random seeds?"
I tried out SDLX-Turbo models, they are working, just need to use the SDXL fix vae. And i'm not impressed at all with the performance. The LCM models are better yet. You can set the batch number on the gui / job. This will generate more image in one batch with increased seed.

"does it support cpu too?"
I tested with cpu, but was sooo slow, so not experimented with it more.

"does img2img works as well?"
not implemented yes in the gui. The backend support it. 

"does it loads gguf files or only safetensors?"

You can find the backend here: https://github.com/leejet/stable-diffusion.cpp
All model types are supported witch supported by the stable-diffusion.cpp latest commit. 


I will make a executable today.

**Comment by Amin456789** [comment] 2024-02-06 08:15
thank u so much for the answer,
1. taesd and taesdxl are supported by sd cpp itself, please add it if possible, withouth these its very time consuming to make images for me the command is --taesd in sd cpp
2. the reason that it was so slow on cpu it is because maybe u need to implenet --threads N from sd cpp so we can choose the maximum core or just make it detect and use all the cores, please try to put it there

thank u for ur hard work, then i guess i will wait for --taesd and maximum cpu and img2img in the future. dark mode at night is very good for the eyes too

**Comment by fszontagh** [comment] 2024-02-06 09:20
1. ok, im on it
2. yes, it's missing from the gui, thanks for the info, added to the todo-s

**Comment by Amin456789** [comment] 2024-02-06 09:27
thank u

**Comment by fszontagh** [comment] 2024-02-06 10:09
Added some binaries: https://github.com/fszontagh/sd.cpp.gui.wx/issues/2

**Comment by Amin456789** [comment] 2024-02-06 10:16
thank u so much

**Comment by JohnClaw** [comment] 2024-02-06 22:29
> Added some binaries: #2

Can't wait for the latest binary version with gguf's detection bug fix.

**Comment by fszontagh** [comment] 2024-02-07 17:28
@JohnClaw @Amin456789  added some new binaries, you can find [here](https://fsociety.hu/sd.cpp.gui.wx/releases/Windows11_preview/)


The following changes made: 

- #5 
- #6 
- #3 
- #8

**Comment by Amin456789** [comment] 2024-02-07 17:34
whoa thank u! u rock!

**Comment by Amin456789** [comment] 2024-02-07 17:37
cant wait for img2img and dark mode, its gonna be so fun. please make a topic in stable diffusion on reddit everytime u make some new changes so people can find it. also ask leejet to put in it his page too

**Comment by JohnClaw** [comment] 2024-02-08 14:06
> The following changes made:

Thanks. Now it loads CPU up to 99% as it should. But nothing happens. 5 minutes passed and no image was created. During "image generation" CPU temperature was 40-41 °C while cli sdd.exe raises it to 55-58 °C when works at 99%.

**Comment by fszontagh** [comment] 2024-02-08 17:41
I don't know what happening :) 

But i waited ~17mins
![image](https://github.com/fszontagh/sd.cpp.gui.wx/assets/51741446/0ef6c5b2-95c8-483f-a931-4d67d1b2be6e)

This is the "avx"  version. 
Are you tried with another version? Which one do you use?

**Comment by JohnClaw** [comment] 2024-02-08 18:08
> Are you tried with another version? Which one do you use?

I use avx2 version. The problem is not in your or my cpu, the problem is in the code of sd.cpp.gui.wx.

**Comment by fszontagh** [comment] 2024-02-08 18:09
Yes, i tried the sd.exe and ind better. 

I think i just messed up the CPU versions.
I'm on it

**Comment by JohnClaw** [comment] 2024-02-08 19:29
Sorry but I know nothing about C++ or C or avx and can't help you with coding, i just hoped that you would make a gui that runs as fast as a cli.

**Comment by fszontagh** [comment] 2024-02-08 19:29
Sry, i just make notes for myself :D

**Comment by fszontagh** [comment] 2024-02-08 21:44
@JohnClaw i created a patch. 
Please download [from here](https://fsociety.hu/sd.cpp.gui.wx/releases/Windows11_preview/AVX2_patch/). I'ts only for avx2. 
Extract it and overwrite the stable-diffusion.dll and ggml.dll with these two in your current runtime directory. 

I really hope it will works.

**Comment by JohnClaw** [comment] 2024-02-08 22:00
> I really hope it will works.

Unforunately, the problem wasn't solved: cpu usage - 99%, cpu temp - 40-41 °C. Still no image was created. And cursor of my mouse was moving very slowly, i barely managed to close the window of sd.cpp.gui.wx.

**Comment by fszontagh** [comment] 2024-02-12 11:39
@JohnClaw please see #10,  i just added a new update

**Comment by JohnClaw** [comment] 2024-02-12 14:40
> @JohnClaw please see #10, i just added a new update

The new update works as fast as cli sd.cpp.exe. Thank you very much.

**Comment by Amin456789** [comment] 2024-02-16 18:13
thank u for the update, but there was a problem with the preview1 = we can't choose output folder no matter how many times we save it, we can choose folder of of everything except this one, i think it doesn't save it in the ini config file, could u please fix it. cant wait for the dark mode too

**Comment by fszontagh** [comment] 2024-02-16 18:33
@Amin456789 thank you for reporting it. I corrected it, and found another one which is corrected too. 
I will publish today a new preview, thats will contain these fixes too.

**Comment by fszontagh** [comment] 2024-02-16 19:59
I just published the current preview. But i forgot to mention, when in the settings is changing something, better to restart the app. Some config changes need a fresh start to getting to live.

**Comment by Amin456789** [comment] 2024-02-16 20:01
thank u so much

**Comment by Amin456789** [comment] 2024-02-16 21:35
it will be great if we can delete jobs and images history and the saved presets include model and taesd and type informaton too

**Comment by fszontagh** [comment] 2024-02-20 18:51
So, added a new preview. The biggest enhancements in it is the drag and drop image (you can drag and drop in image into the text2img or img2img tab). 
And changed the default output image type from png to jpeg. Smaller files, but the generation parameters is stored in it. So if you drop the generated image into the gui, it can detect the generation informations from the image.

**Comment by fszontagh** [comment] 2024-11-07 17:54
So, i close this. 
Some of this features are implemented into the gui. 
In the next prerelease i added the convert feature (convert safetensors checkpoints into gguf, may its called "quantization"?).
And got a really big update the gui. 
Only the dark mode (#4)  which waiting for external update.

**Closed by fszontagh** 2024-11-07 17:54 UTC
Labels: question
